### ISSUE TITLE
Improve performance of tests

### ISSUE THREAD

**Issue by elrayle** [projecthydra-labs/hydra-pcdm#118]
Several proposals were made for improving the overall performance of tests.
* create objects used in tests in a before all block - NOTE: There can be bleed over between tests and multiple failing tests caused by this bleed over.  Care needs to be taken in selecting areas of tests where this improvement can be applied.
* use mockups instead of connecting to Fedora - NOTE: Corresponding improvements need to be made at the ActiveFedora level to have confidence that the removal of this connection won't let failures slip through
* move edge tests to lower levels (e.g. ActiveFedora) and remove from Hydra:PCDM

**Comment by mjgiarlo** [comment]
:+1:

**Comment by elrayle** [comment]
Baseline Performance for basic functions  (generated by [spec/performance_tests](https://github.com/projecthydra-labs/hydra-pcdm/tree/performance_tests/spec/performance_tests) in performance_tests branch)
```
============================================
 Create 1 collection (10 repetitions)
============================================
 create approach       total time (s)   per object time (s)
--------------------   --------------   -------------------
new                     0.01392198       0.00139220
create                  1.31239271       0.13123927

============================================
 Adding one collection to a collection (10 repetitions)
============================================
    add approach       total time (s)   per object time (s)
--------------------   --------------   -------------------
members <<              7.21745777       0.72174578
collections=            6.98528314       0.69852831
service call            6.90817666       0.69081767

============================================
 Adding one object to a collection (10 repetitions)
============================================
    add approach       total time (s)   per object time (s)
--------------------   --------------   -------------------
members <<              7.06119347       0.70611935
objects=                6.99220324       0.69922032
service call            7.03307724       0.70330772
```

**Comment by elrayle** [comment]
My understanding of the difference between new and create is that create = new + persist to Fedora.  Can someone confirm that is the only difference?
