### ISSUE TITLE
Ancestor test fails when collections/objects aren't saved

### ISSUE THREAD

**Issue by elrayle** [projecthydra-labs/hydra-pcdm#119]
ancestor? test checks ids aren't equal.  So when collections/objects aren't saved, this fails because all ids are nil and therefore are equal.

Recommendation: do object equality instead of id equality

**Comment by elrayle** [comment]
Fixed by pull request https://github.com/projecthydra-labs/hydra-pcdm/pull/120

**Comment by elrayle** [comment]
Based on feedback, there is a preference for checking the ids if they exist and only doing object equality when either the parent or child has a nil id.

**Comment by terrellt** [comment]
@elrayle Ah, sorry, I may have been hasty then. I thought since the edge cases were handled via object equivalence that we didn't want to handle it again.

**Comment by elrayle** [comment]
Based on discussions in the following issues, object equivalence is the most efficient approach.  Testing of object equivalence is inherited from ActiveFedora:Base [core.rb](https://github.com/projecthydra/active_fedora/blob/master/lib/active_fedora/core.rb) == method.

* https://github.com/projecthydra/active_fedora/issues/849
* https://github.com/projecthydra-labs/hydra-pcdm/pull/122
