### ISSUE TITLE
Set rdf:type on Collection

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/hydra-pcdm#12]
I saw this code in the collection:
```ruby
# configure :type => RDFVocabularies::PCDMTerms.Collection  # FIX: This is how ActiveTriples sets type, but doesn't work in ActiveFedora
```

It can now be written as:
```ruby
  type RDFVocabularies::PCDMTerms.Collection 
```

**Comment by flyingzumwalt** [comment]
I think this is ready to close, based on this line here: https://github.com/projecthydra-labs/hydra-pcdm/blob/master/lib/hydra/pcdm/models/concerns/collection_behavior.rb#L6
