### ISSUE TITLE
Invalid next/prev links after removing middle member

### ISSUE THREAD

**Issue by escowles** [projecthydra-labs/hydra-pcdm#133]
When I remove the middle item of an ordered members list, as in:

https://github.com/projecthydra-labs/hydra-pcdm/blob/master/spec/hydra/pcdm/services/collection/remove_object_spec.rb#L62

The members that were next to the removed item then have next/prev links pointing to themselves:

object1 iana:next object2
object2 iana:prev object1
object2 iana:next object4
**object2 iana:next object2**
object4 iana:prev object2
**object4 iana:prev object4**
object4 iana:next object5
object5 iana:prev object4

**Comment by terrellt** [comment]
@escowles I think this was fixed by https://github.com/projecthydra/active_fedora/pull/863. Can you confirm?

**Comment by escowles** [comment]
Yes, I can confirm this is fixed.  We're not persisting the relevant test objects to Fedora in our tests now, but if you update the [test that removes a middle member](https://github.com/projecthydra-labs/hydra-pcdm/blob/5dd1c26c23b11847f71aaa3437259bad6d9d8346/spec/hydra/pcdm/models/collection_spec.rb#L189-L192) to save, then the triples are now as expected with no broken next/prev links.
