### ISSUE TITLE
should not be able to add a collection as a child of an object

### ISSUE THREAD

**Issue by elrayle** [projecthydra-labs/hydra-pcdm#135]
obj.members = [col]    # should raise ActiveFedora::AssociationTypeMismatch col is not a PCDM object.

See test pcdm/models/object_spec.rb #members with unacceptable child objects it should NOT aggregate Hydra::PCDM::Collection in objects aggregation around line 206

**Comment by escowles** [comment]
This was resolved with https://github.com/escowles/hydra-pcdm/commit/e9b8c7430bfd3c1bb8c0fbf6b79ae2227fcf4cb2
