### ISSUE TITLE
Remove atomic service objects

### ISSUE THREAD

**Issue by elrayle** [projecthydra-labs/hydra-pcdm#142]
The following service objects are being replaced with the new API.

* AddXToY
* GetXFromY
* RemoveXFromY

Deprecate service objects with a target removal date.

**Comment by elrayle** [comment]
Blocked by issues https://github.com/projecthydra-labs/activefedora-aggregation/issues/52 and https://github.com/projecthydra-labs/activefedora-aggregation/issues/51.

**Comment by mjgiarlo** [comment]
@jcoyne suggests that this is no longer blocked (per the 7/16 scrum)

**Comment by elrayle** [comment]
In reality, the failures still exist for all remove services.  I've marked them pending and reference the issue in the failing tests.  See issue https://github.com/projecthydra-labs/activefedora-aggregation/issues/52

**Comment by elrayle** [comment]
This does not include...
* deprecation of related object services. See https://github.com/projecthydra-labs/hydra-pcdm/issues/146
* move tests as appropriate from service object tests for deprecated services to models/object_spec and collection_spec

**Comment by elrayle** [comment]
Fixed by https://github.com/projecthydra-labs/hydra-pcdm/pull/144
