### ISSUE TITLE
obj.members should not allow an ActiveFedora::Base to be a member

### ISSUE THREAD

**Issue by elrayle** [projecthydra-labs/hydra-pcdm#143]
The following should raise NoMethodError, but it raises nothing.

```ruby
        expect { @object101.members = [@af_base_object] }.to raise_error(error_type,error_message)
```

See object_spec.rb around line 246, test it 'should NOT aggregate AF::Base objects in objects aggregation'
.

**Comment by elrayle** [comment]
Is this fixed?

**Comment by terrellt** [comment]
The test is green and not marked pending, so it should be!

**Comment by terrellt** [comment]
I think I was looking at the wrong test.

**Comment by jcoyne** [comment]
Can someone explain this behavior to me? If it should exclude objects that extend from ActiveFedora::Base, what else is left?

**Comment by jcoyne** [comment]
Should it say "It excludes objects that are not PCDM::Objects?"

**Comment by terrellt** [comment]
@jcoyne I think the validation is "if you add something it should respond to `pcdm_object?`/`pcdm_collection?`

**Comment by terrellt** [comment]
> Should it say "It excludes objects that are not PCDM::Objects?"

:+1:
