### ISSUE TITLE
move deprecated service object tests to object/collection_spec tests

### ISSUE THREAD

**Issue by elrayle** [projecthydra-labs/hydra-pcdm#147]
Issue https://github.com/projecthydra-labs/hydra-pcdm/issues/142 deprecated the atomic service objects.  The tests were not moved as part of that process.  Tests that continue to apply (most tests) need to be moved from the [service object tests](https://github.com/projecthydra-labs/hydra-pcdm/tree/master/spec/hydra/pcdm/services) to models/object_spec or collection_spec.

**Comment by escowles** [comment]
I think there's some missing validation functionality, where the tests that validate the arguments to services can't really be replaced when dealing with the objects directly (see https://github.com/projecthydra-labs/hydra-pcdm/issues/153).

I'll keep moving them over and just marking them pending as I find cases like this.
