### ISSUE TITLE
Improve models validation of members collection/objects and related objects

### ISSUE THREAD

**Issue by escowles** [projecthydra-labs/hydra-pcdm#153]
Several of the service objects do validation of their arguments that can't be done with the indirectly_contains/filters_associations approach directly.

For example, AddRelatedObjectToCollection does validation on the objects being added to make sure they are PCDM::Objects, but collection.related_objects accepts any AF::Base when added directly.

See #135

**Comment by terrellt** [comment]
I'm working on the type validations for #143 now, which should give us a good pattern for moving forward.

**Comment by escowles** [comment]
@terrellt, that looks like great functionality -- can we use the type_validator on filters_association and indirectly_contains too?

**Comment by terrellt** [comment]
@escowles No, but I wonder if it's a nice enough feature to push all the way down to association.rb in AF. @jcoyne?

**Comment by jcoyne** [comment]
Is there's any reason not to?

**Comment by mjgiarlo** [comment]
Type validation is now pushed down into AF.  Worth removing the skipped tests and getting those passing?
