### ISSUE TITLE
Rework association names. drop parent_ and child_

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/hydra-pcdm#180]
```
child_collections  -> collections
parent_collections -> in_collections
child_works -> works
parent_works -> in_works
```

**Comment by elrayle** [comment]
Also effected...
* pcdm_behavior.rb#parents -> #is_member_of
* pcdm_behavior.rb#parent_collection_ids -> #in_collection_ids

NOTE: no method for...
* object_behavior.rb#parent_objects_ids

NOTE:  Adding deprecation messages for change methods to avoid problems with apps using these methods.  Deprecation end date 10-31-2015.

**Comment by elrayle** [comment]
Rubocop doesn't like #is_member_of.  Changed it to #members_of
