### ISSUE TITLE
Remove deprecated methods scheduled for 10-31-2015

### ISSUE THREAD

**Issue by elrayle** [projecthydra-labs/hydra-pcdm#183]
Search for DEPRECATION and 10-31-2015.  Any method with both those markers should be removed.  

NOTE: There are several tests that check that the deprecated methods continued to work during the deprecation time period.  Those also need to be removed.  You can find them when they fail once the deprecated methods are removed.  Also, they have a test message like 'deprecated methods should pass'.

**Comment by jeremyf** [comment]
@elrayle I'm not seeing any DEPRECATION notices. I'm closing this. But feel free to re-open.
