### ISSUE TITLE
Filtered Ordered Associations Shouldn't be Settable

### ISSUE THREAD

**Issue by terrellt** [projecthydra-labs/hydra-pcdm#185]
I ran into this while working on moving the new AF::Aggregations work over here.

What does it mean to set `#objects`, or append to `#objects`? The way it worked before was "append anything to the end of the list", but that does unexpected things to the order as a whole - because ordering is at the member level, not at the PCDM::Object level. For instance:

```ruby
col1 = Collection.new
col2 = Collection.new
m1 = Member.new
m2 = Member.new
col1.ordered_members += [m1, col2, m2]
# Reorder objects
col1.objects # => [m1, m2]
col1.objects = [m2, m1]
col1.ordered_members [col2, m2, m1] # => This is definitely wrong, but it's easy to happen, because we're ordering out of context. Things get even worse when you start trying to delete.
```

My proposal is this: Only #members, #ordered_members, and #ordered_member_proxies should be settable.

**Comment by mjgiarlo** [comment]
:+1: to that suggestion.

**Comment by jcoyne** [comment]
Yeah, that sounds good.
