### ISSUE TITLE
Create Concrete Model classes

### ISSUE THREAD

**Issue by cam156** [projecthydra-labs/hydra-pcdm#2]
Create the following Model Classes:
Hydra::PCDM::Condiment (will be an Non RDF source)
Hydra::PCDM::Cheese (will include PCDM::Object)
Hydra::PCDM::Meat (will include PCDM::Object)
Hydra::PCDM::Bread (will include PCDM::Object)
Hydra::PCDM::Sandwich (will include PCDM::Collection)

They should inherit from active fedora base

**Comment by cam156** [comment]
The intention is these are for use and testing, but we are not expecting Sufia to use them.

**Comment by jeremyf** [comment]
The concrete class is used for validating the interfaces. See #3 and #4 for reference about interfaces.
