### ISSUE TITLE
Initial Implementation of PCDM::Object and PCDM::Collection 

### ISSUE THREAD

**Issue by flyingzumwalt** [projecthydra-labs/hydra-pcdm#20]
See specifications for [PCDM::Object](https://wiki.duraspace.org/display/FF/Portland+Common+Data+Model#PortlandCommonDataModel-pcdm:Object) and [PCDM::Collection](https://wiki.duraspace.org/display/FF/Portland+Common+Data+Model#PortlandCommonDataModel-pcdm:Collection)

Note: Enforcement of Behavior Rules is handled in #23.  Talk to @awead about what you need to do in your implementation to support that. 

Existing Code, which includes some notes about implementation: https://github.com/projecthydra-labs/hydra-pcdm/tree/feature_initial_model/lib/hydra/pcdm/models  Currently on the feature_initial_model branch, but soon to be merged into master.

**Comment by flyingzumwalt** [comment]
Related Tickets: #14 #13

**Comment by elrayle** [comment]
Related ticket: #43 
Will close when 43 is committed to master.
