### ISSUE TITLE
Make sure RDF Properties on the PCDM Domain Model Page are correct

### ISSUE THREAD

**Issue by flyingzumwalt** [projecthydra-labs/hydra-pcdm#21]
Review the [PCDM domain model page](https://www.google.com/url?q=https%3A%2F%2Fwiki.duraspace.org%2Fdisplay%2FFF%2FPortland%2BCommon%2BData%2BModel%23PortlandCommonDataModel-DomainModel&sa=D&sntz=1&usg=AFQjCNFBnej81O3esZDljJ6jEpym--J68Q) and confirm that all RDF properties are correct

**Comment by escowles** [comment]
I'm reviewing the PCDM properties page.

**Comment by escowles** [comment]
The Collection and Object properties are correct and match what's in the ontology:

https://github.com/duraspace/pcdm/blob/master/models.rdf

For the File properties, there is a new draft from the Hydra Metadata Working Group that proposes using different properties for technical metadata than what's on the Fedora wiki:

https://docs.google.com/document/d/1SZCpSIdlGfXgoYrAnW2eRKlIt6O-1ADIDDhmLrvxeLc/edit

**Comment by flyingzumwalt** [comment]
:+1:

**Comment by flyingzumwalt** [comment]
Assigning this to myself now.  I'll close it after updating the fedora wiki with info about the new Technical Metadata specs.

**Comment by acoburn** [comment]
I just put the draft technical metadata profile on the duraspace wiki: https://wiki.duraspace.org/display/hydra/Technical+Metadata+Application+Profile

It would be useful to add any comments or make changes directly on that page.

**Comment by flyingzumwalt** [comment]
Thanks @acoburn.  Updated the wiki to reflect this info.
