### ISSUE TITLE
Should validator's return a value?

### ISSUE THREAD

**Issue by jeremyf** [projecthydra-labs/hydra-pcdm#215]
At present the existing validators either raise an exception or return nil. As a developer, I would not assume a `nil` return value to indicate success.

**Comment by tpendragon** [comment]
I guess I never considered the return value to be part of the interface. Defining a boolean return seems reasonable?

**Comment by jeremyf** [comment]
I haven't yet oriented myself to how the PCDM validators are consumed, but was thinking of what I would expect. I believe adding `return true` would be a non-breaking change to the interface.

**Comment by jeremyf** [comment]
As I was looking at the validators, the CompositeValidator relies on exceptions and doesn't care about return values.

The validators also do not have unit specs to define their interface, so that would be something to add as well.

**Comment by jeremyf** [comment]
As I explored the issue, I feel this is low hanging fruit.
