### ISSUE TITLE
pcdm:Collections, pcdm:Objects and pcdm:Files enforce behavior rules

### ISSUE THREAD

**Issue by flyingzumwalt** [projecthydra-labs/hydra-pcdm#23]
Note: If it's not possible to enforce these rules on Files for some reason, call it out on the scrum.

## Object Behavior Rules

- [x] Hydra::PCDM::Object can aggregate (pcdm:hasMember) Hydra::PCDM::Object
- [x] Hydra::PCDM::Object can aggregate (ore:aggregates) Hydra::PCDM::Object  (Object related to the Object)
- [x] Hydra::PCDM::Object can contain (pcdm:hasFile) Hydra::PCDM::File
- [ ] Hydra::PCDM::Object can contain (pcdm:hasRelatedFile) Hydra::PCDM::File
- [x] Hydra::PCDM::Object can NOT aggregate Hydra::PCDM::Collection
- [x] Hydra::PCDM::Object can NOT aggregate non-PCDM object
- [ ] Hydra::PCDM::Object can have descriptive metadata
- [ ] Hydra::PCDM::Object can have access metadata

## File Behavior Rules
- [ ] N/A - PCDM::File can NOT aggregate anything  (no aggregation, so nothing to test)
- [ ] N/A - PCDM::File can NOT contain PCDM::File  (no contains association defined, so nothing to test)
- [ ] PCDM::File can have technical metadata about one uploaded binary file

## Collection Behavior Rules

- [x] Hydra::PCDM::Collection can aggregate (pcdm:hasMember) Hydra::PCDM::Collection
- [x] Hydra::PCDM::Collection can aggregate (pcdm:hasMember) Hydra::PCDM::Object
- [x] Hydra::PCDM::Collection can aggregate (ore:aggregates) Hydra::PCDM::Object (Object related to the Collection)
- [x] Hydra::PCDM::Collection can NOT aggregate non-PCDM object
- [x] Hydra::PCDM::Collection can NOT contain Hydra::PCDM::File
- [ ] Hydra::PCDM::Collection can have descriptive metadata
- [ ] Hydra::PCDM::Collection can have access metadata

**Comment by elrayle** [comment]
Notes:
* Most of these are now covered by PR https://github.com/projecthydra-labs/hydra-pcdm/pull/79 and previous commits that added tests.
* Object hasRelatedFiles Object is covered by PR https://github.com/projecthydra-labs/hydra-pcdm/pull/66
* See PR https://github.com/projecthydra-labs/hydra-pcdm/pull/70 for a discussion on technical metadata.

Outstanding Questions:
* Descriptive metadata is handled via properties set on subclasses.  Should this be tested at pcdm level?
* Access metadata is TBD

**Comment by elrayle** [comment]
Questions related to descriptive and access metadata:
* How to distinguish between descriptive and access metadata?
* Are there any default properties to set for Collection's descriptive metadata?
* Are there any default properties to set for Collection's access metadata?
* Is there a way to override default properties defined in this class?

**Comment by elrayle** [comment]
Per scrum call...
* descriptive metadata is tested at the active-fedora level for properties and can be tested at a level beyond Hydra:Works where properties are defined
* access metadata will be tested under a separate ticket

Remaining unchecked items will be tested separately.  See notes in previous comment.

Closing this issue.
