### ISSUE TITLE
Supported ruby versions

### ISSUE THREAD

**Issue by awead** [projecthydra-labs/hydra-pcdm#25]
At present, Travis is testing multiple Ruby versions 1.9 through 2.1, as well as jruby. Are all those needed? Perhaps we can just to 2.1 and 2.2? @jcoyne @elrayle ?

**Comment by no-reply** [comment]
It may be worth noting that future releases of `ActiveTriples` and `ruby-rdf` will not support 1.9.

**Comment by awead** [comment]
@no-reply yeah, I already pulled it from the test because we're using pry-byebug and that's 2.0 only.

**Comment by cbeer** [comment]
The only reason to support Ruby 1.9 is to support JRuby until JRuby 9000 is released. MRI 1.9.3 itself is EOLed earlier this year and I don't think new code should go out of its way to support it.

**Comment by atz** [comment]
I can configure gemspec and travis to build 1.9 jruby while excluding pry-byebug, if desired.

**Comment by awead** [comment]
@atz Travis isn't installing byebug anymore thanks to 4229fda9c396bc76eb290ab4cba53868eb21dab0 but we appreciate the offer! :smile: 
@cbeer Travis is currently testing jruby, but allowing failures. Does that mean we need to test Ruby 1.9 as well? If so, I can put it back in the matrix. Otherwise, what else needs to be done?

**Comment by jcoyne** [comment]
I updated to jruby 9000 and the build works. https://travis-ci.org/projecthydra-labs/hydra-pcdm/jobs/62086666
