### ISSUE TITLE
Create class Hydra::PCDM::Interfaces::CollectionInterface and aggregate Collections & Objects

### ISSUE THREAD

**Issue by elrayle** [projecthydra-labs/hydra-pcdm#27]
Create Hydra::PCDM::Interfaces::CollectionInterface

Should be able to aggregate pcdm:Collections using the pcdm:hasMember 
Should be able to aggregate pcdm:Objects using the pcdm:hasMember 

Should not be able to contain pcdm:File

**Comment by elrayle** [comment]
Re-work as module.

**Comment by elrayle** [comment]
This is completed by PR https://github.com/projecthydra-labs/hydra-pcdm/pull/41.

**Comment by awead** [comment]
@elrayle is this done? If so, I can work on #23
