### ISSUE TITLE
Generate CollectionInterface

### ISSUE THREAD

**Issue by cam156** [projecthydra-labs/hydra-pcdm#3]
Create modules
Hydra::PCDM::Interfaces::CollectionInterface (this is a module)
   Should be able to aggregate pcdm:Objects using the pcdm:hasMember (eg Hydra::PCDM::GenericWork)
   Should be able to aggregate pcdm:Collection using the pcdm:hasMember (eg Hydra::PCDM::Collection)

* Should not be able to contain files
* There can be zero to many Objects
* There can be zero to many Collections

**Comment by cam156** [comment]
This is dependent on #4

**Comment by cam156** [comment]
Use work work done in #4 for an example of how to implement

**Comment by flyingzumwalt** [comment]
Is this still relevant?

**Comment by flyingzumwalt** [comment]
Is this a repetition of #23?

**Comment by awead** [comment]
@flyingzumwalt this looks like cardinality. There isn't anything in #23 about that.

**Comment by elrayle** [comment]
This really is a dup of https://github.com/projecthydra-labs/hydra-pcdm/issues/27 which is closed.  Closing this issue.
