### ISSUE TITLE
Create class Hydra::PCDM::Interfaces::ObjectInterface and aggregate Objects

### ISSUE THREAD

**Issue by cam156** [projecthydra-labs/hydra-pcdm#4]
Create Hydra::PCDM::Interfaces::ObjectInterface

   Should be able to aggregate pcdm:Objects using the pcdm:hasMember (eg Hydra::PCDM::GenericWork)

  Should not be able to aggregate pcdm:Collection (eg Hydra::PCDM::Collection)

**Comment by elrayle** [comment]
Need to re-work as module.

**Comment by elrayle** [comment]
This is mostly done.  Needs tests.

**Comment by elrayle** [comment]
Related ticket: #43 
Will close when 43 is committed to master.
