### ISSUE TITLE
implement << operator on collections

### ISSUE THREAD

**Issue by elrayle** [projecthydra-labs/hydra-pcdm#45]
ideally the << operator would work like...

```
coll1.collections << coll2
coll1.objects << obj1
```

But collections is a method and not a ruby object.  A method cannot have the << operator.

Alternative is...

```
coll1 << coll2
coll1 << obj1
```

**Comment by terrellt** [comment]
Is it a common use case to want the collections separate from the objects?

**Comment by elrayle** [comment]
I'll have to let others speak to this.  I could see an app that wants to display collections grouped at the top of a list and objects grouped at the bottom of the list.  With the code as it currently exists, the app could either request...
* colls = coll1.collections         # just get collections in order
* objs = coll1.objects               # just get objects in order
* members = coll1.members   # get collections and objects intermixed in order

This ticket has to do with appending collections and objects.

**Comment by elrayle** [comment]
There are several tests in collection_spec that attempt to use << to add collections and objects.  The test may need to be adjusted depending on the implementation approach.  They are all currently marked xit to skip them since they are known failures.

**Comment by jcoyne** [comment]
I don't think we should do this.  The `<<` operator would imply that a collection is the sum of its contained items (e.g. like an Array), but a collection is more than that, it has descriptions too.

**Comment by flyingzumwalt** [comment]
I agree with @jcoyne about putting the operator directly on instances of a collection.  It should be `coll1.members << obj1`, not `coll1 << obj1`.  See how this is handled by ActiveFedora::Associations (digging up links. one sec)

**Comment by flyingzumwalt** [comment]
I suspect that you will have to do something like [ActiveFedora::Associations::CollectionAssociation](https://github.com/projecthydra/active_fedora/blob/master/lib/active_fedora/associations/collection_association.rb)

**Comment by flyingzumwalt** [comment]
Question:  Is it the case that this is NOT a problem with `.members <<` and is only a problem with `.collections <<` and `.objects <<`?  

If it's a problem with all three, then the underlying code (in AF::Aggregation) needs to do something like ActiveFedora::Associations, which adds the necessary methods to Collection and makes those methods return something like ActiveFedora::CollectionAssociation instead of an Array.

If, on the other hand, `.members<<` already works fine (meaning the underlying code is doing the right thing), then I would have different ideas about how to make `.collections<<` or `.objects<<` work.

**Comment by terrellt** [comment]
#members << doesn't work, but there's a ticket for it. It -should-.

**Comment by terrellt** [comment]
https://github.com/projecthydra-labs/activefedora-aggregation/issues/22

**Comment by terrellt** [comment]
I'd want something like this...
```ruby
def collections
  AssociationTypeFilter.new(members, PCDM::Collection)
end

class AssociationTypeFilter < SimpleDelegator
  attr_reader :type
  def initialize(members, type)
    @type = type
    super(members)
  end
  def to_a
    __getobj__.to_a.select{|x| x.rdf_type == type}
  end
end
```

Note that #to_a won't work, because I don't know the API for getting an AF::Base's type, but yeah.

**Comment by flyingzumwalt** [comment]
I've added some implementation suggestions to projecthydra-labs/activefedora-aggregation#22.  

Note that with regular ActiveModel Associations you can simply add a second `has_many` (or `has_and_belongs_to_many` association and make it filter the objects differently, expect different classes, etc.  Obviously, you can't to allow people to call `aggregates` multiple times, but maybe that's just a matter of having a second method like `filters_aggregation`
