### ISSUE TITLE
Superclass Method Error in Hydra::PCDM::Object

### ISSUE THREAD

**Issue by kevinreiss** [projecthydra-labs/hydra-pcdm#55]
In https://github.com/projecthydra-labs/hydra-works/blob/gen_work_has_gen_files/spec/models/hydra/works/generic_file_spec.rb calling contains= raises

```
 Failure/Error: generic_file.contains = [file1, file2]
     NoMethodError:
       super: no superclass method `contains=' for #<Hydra::Works::GenericFile:0x007ff0d70dba68>
```

See https://github.com/projecthydra-labs/hydra-works/issues/58

**Comment by jcoyne** [comment]
The API will be PCDM::Object#files not #contains=  Of course this depends on https://github.com/projecthydra-labs/hydra-pcdm/pull/52

**Comment by jcoyne** [comment]
@kevinreiss Can this be closed?

**Comment by kevinreiss** [comment]
@jcoyne yes I think it can when #52 is merged.
