### ISSUE TITLE
setup service architecture

### ISSUE THREAD

**Issue by elrayle** [projecthydra-labs/hydra-pcdm#57]
create the following directory structure in Hydra::Works
````
\lib\hydra\works\services
     \collection
     \generic_work
     \generic_file
     \file
````

**Comment by jcoyne** [comment]
Should this ticket be moved to https://github.com/projecthydra-labs/hydra-works?

**Comment by flyingzumwalt** [comment]
Moved the ticket to projecthydra-labs/hydra-works#62.
