### ISSUE TITLE
Make validation callable from other classes

### ISSUE THREAD

**Issue by elrayle** [projecthydra-labs/hydra-pcdm#60]
**Need:**  ability to validate a collection or object from services and tests

**Recommendation:**

* change Collection's collection? method to a class method
* move Collection's object? method to PCDM::Object and make it a class method
* have all validations call the class methods

**Comment by elrayle** [comment]
@awead Can you take a look at this?  Let me know if not and I'll take care of it.

**Comment by elrayle** [comment]
Playing around with this in my tests, it isn't quite as simple a change.   Tried...

def self.collection?

Since the method is defined by including from collection_behavior, it doesn't appear to go onto the Hydra::PCDM::Collection class.  When I try to use it, I get...

undefined method `collection?' for Hydra::PCDM::Collection:Class

**Comment by jcoyne** [comment]
You need to put it in the ClassMethods module under CollectionBehavior

**Comment by elrayle** [comment]
That works.  Thanks.

**Comment by elrayle** [comment]
Fixed by PR #65.
