### ISSUE TITLE
Complete the Hydra::PCDM::Meat

### ISSUE THREAD

**Issue by cam156** [projecthydra-labs/hydra-pcdm#7]
Include the Hydra::PCDM::Interfaces::Object

Should be able to contain Condiments
Should not be able to aggregate Sandwich
Should not be able to aggregate Bread

**Comment by jpstroop** [comment]
[PCDM](https://wiki.duraspace.org/display/FF/Portland+Common+Data+Model) doesn't have a GenericFile. `Sufia::PCDM::GenericFile` ??

**Comment by mjgiarlo** [comment]
```ruby
module Sufia
  class GenericFile < Hydra::PCDM::Object
  end
end
```

:question:

**Comment by cam156** [comment]
Based on the discussion we are putting concrete classes to implement the small model GenericFile, GenericWork, Collection as described by the modeling for sufia.  These concrete classes are used for testing and examples, but not as things that Sufia uses

**Comment by jpstroop** [comment]
OK thanks, that helps, but I still think putting them in the PCDM namespace could lead to confusion.

**Comment by azaroth42** [comment]
Please don't further confuse implementers with Sufia specific terminology in *PCDM* implementations. Clear separation of Sufia and PCDM would be appreciated.

**Comment by hectorcorrea** [comment]
For reference to others:
Ticket #7 implements the equivalent of a PCDM::File (this ticket)
Ticket #8 implements the equivalent of a PCDM::Work
Ticket #9 implements the equivalent of a PCDM::Collection
