### ISSUE TITLE
Ruby 2.2 regex error

### ISSUE THREAD

**Issue by atz** [projecthydra-labs/hydra-pcdm#75]
https://travis-ci.org/projecthydra-labs/hydra-pcdm/jobs/62103870#L232
```
 RegexpError:
       premature end of char-class: /\A[\x20-\x21\x23-\x5B\x5D-\x7E]*\z/m
```

**Comment by hectorcorrea** [comment]
@atz The error seems to point to this line of code: https://github.com/ruby-rdf/rdf/blob/develop/lib/rdf/ntriples/writer.rb#L58

However, I cannot reproduce the error when I execute the code in question:

```
ESCAPE_PLAIN = /\A[\x20-\x21\x23-\x5B\x5D-\x7E]*\z/m.freeze
string = "11"
string =~ ESCAPE_PLAIN
```

When I execute this code in IRB I get 0 (as expected) but when I run this code through my RSpec test (https://github.com/projecthydra-labs/hydra-pcdm/pull/70/files#diff-f235bfb80c4de96254fae123aeb0785eR33) I get 

```
warning: character class has ']' without escape: /\A[ -!#-[]-~]*\z/
*** RegexpError Exception: premature end of char-class: /\A[\x20-\x21\x23-\x5B\x5D-\x7E]*\z/m
```

It's worth nothing that this only happens with Ruby 2.2 (but not with Ruby 2.1)

**Comment by hectorcorrea** [comment]
Additionally, I can only make this error happen when assigning a number to a property and then the property is (automatically) converted to string. The problem does not happen when the property is initially set to a string.

**Comment by atz** [comment]
Maybe we can get around this with notation like `\x{21}\x{23}` since this seems to involve the interpretation of `\x7E]` as a single entity.  Unable to reproduce locally:

```
Administrators-MacBook-Pro-3:hydra-pcdm atz$ rvm list

rvm rubies

   ruby-1.9.3-p547 [ x86_64 ]
 * ruby-2.1.2 [ x86_64 ]
=> ruby-2.2.0 [ x86_64 ]

# => - current
# =* - current && default
#  * - default

Administrators-MacBook-Pro-3:hydra-pcdm atz$ rake ci
I, [2015-05-11T13:48:01.399549 #32691]  INFO -- : Unpacking tmp/master.zip...
running continuous integration
W, [2015-05-11T13:48:02.016712 #32691]  WARN -- : Didn't find expected jettywrapper config file at ./config/jetty.yml, using default file instead.
D, [2015-05-11T13:48:02.017917 #32691] DEBUG -- : Starting jetty with these values: 
D, [2015-05-11T13:48:02.017954 #32691] DEBUG -- : jetty_home: /Users/atz/repos/hydra-pcdm/jetty
D, [2015-05-11T13:48:02.018008 #32691] DEBUG -- : jetty_command: java -Djetty.port=8983 -Dsolr.solr.home=/Users/atz/repos/hydra-pcdm/jetty/solr -XX:MaxPermSize=256m -Xmx256m -jar start.jar
W, [2015-05-11T13:48:02.018683 #32691]  WARN -- : Logging jettywrapper stdout to /Users/atz/repos/hydra-pcdm/jetty/jettywrapper.log
D, [2015-05-11T13:48:02.023727 #32691] DEBUG -- : Wrote pid file to /Users/atz/repos/hydra-pcdm/tmp/pids/_Users_atz_repos_hydra-pcdm_jetty_development.pid with value 32695
I, [2015-05-11T13:48:12.053050 #32691]  INFO -- : Started jetty (10034.8ms)
/Users/atz/.rvm/rubies/ruby-2.2.0/bin/ruby -I/Users/atz/.rvm/gems/ruby-2.2.0/gems/rspec-support-3.2.2/lib:/Users/atz/.rvm/gems/ruby-2.2.0/gems/rspec-core-3.2.3/lib /Users/atz/.rvm/gems/ruby-2.2.0/gems/rspec-core-3.2.3/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb
[Coveralls] Set up the SimpleCov formatter.
[Coveralls] Using SimpleCov's default settings.
.*..............*.............*.....*

Pending: (Failures listed here are expected and do not affect your suite's status)

  1) Hydra::PCDM::Collection#collections= should add a collection to the collections aggregation
     # Temporarily skipped with xit
     # ./spec/hydra/pcdm/models/collection_spec.rb:40

  2) Hydra::PCDM::Collection#objects= should add an object to the objects aggregation
     # Temporarily skipped with xit
     # ./spec/hydra/pcdm/models/collection_spec.rb:174

  3) Hydra::PCDM::Object#objects= should add an object to the objects aggregation
     # Temporarily skipped with xit
     # ./spec/hydra/pcdm/models/object_spec.rb:36

  4) Hydra::PCDM::Object#related_files should contain related files
     # Temporarily skipped with xit
     # ./spec/hydra/pcdm/models/object_spec.rb:104


Finished in 43.33 seconds (files took 1.64 seconds to load)
37 examples, 0 failures, 4 pending

[Coveralls] Outside the CI environment, not sending data.
D, [2015-05-11T13:48:57.229155 #32691] DEBUG -- : Instance stop method called for pid '32695'
```

**Comment by hectorcorrea** [comment]
I couldn't come with a contrived code example to reproduce this either. In the end the error stopped being triggered by other changes that I made to the code. I suspect that the error might be due to some monkey patching along the way and not the code in `writer.rb` that is throwing the exception. 

I would vote for closing this issue.

**Comment by atz** [comment]
@hectorcorrea, the code you referenced offers a comment for the REGEXs linking to:
  http://www.w3.org/TR/rdf-testcases/#ntrip_strings

Notably that page says "do not link to this page—use dated versions of the documents", of which there are two versions: 2004 and 2014.  I think the meat of what it wants to reference is in the 2004 version:

http://www.w3.org/TR/2004/REC-rdf-testcases-20040210/#ntrip_strings

That specifies the three ranges combined in `/\A[\x20-\x21\x23-\x5B\x5D-\x7E]*\z/m` where the character maps to itself.

But if you circumvented the problem another way, that's good enough for me.  Closing.
