### ISSUE TITLE
Complete the Hydra::PCDM::Bread

### ISSUE THREAD

**Issue by cam156** [projecthydra-labs/hydra-pcdm#8]
Include the Hydra::PCDM::Interfaces::Object

Should be able to aggregate Meat & Cheese
Should not be able to contain Condiments
Should not be able to aggregate Bread
(future) Should be able to aggregate Bread

**Comment by jpstroop** [comment]
[PCDM](https://wiki.duraspace.org/display/FF/Portland+Common+Data+Model) doesn't have a GenericWork. `Sufia::PCDM::GenericWork` ??

**Comment by cam156** [comment]
@jpstroop This is an example class. This is the hydra version of PCDM so it can be different than PCDM.

**Comment by azaroth42** [comment]
-1 to calling anything PCDM when it's NOT part of ... you know ... PCDM.  Please rename.

**Comment by jpstroop** [comment]
> This is the hydra version of PCDM so it can be different than PCDM.

But then what's the point of a shared model. Hydra _implementation_ +1, Hydra "version", -1.
