### ISSUE TITLE
Fix append tests

### ISSUE THREAD

**Issue by elrayle** [projecthydra-labs/hydra-pcdm#82]
<< works at active fedora level and is implemented correctly in pcdm.  The tests do not test it correctly. 

coll1.collections << coll2   # not supported
coll1.objects << obj1  # not supported
coll1 << coll2  # is supported
coll1 << obj1  # is supported

This may not be as clear to the end user.  But it is operational now.  Tests are being updated to reflect what is supported.

**Comment by jcoyne** [comment]
No. We should not support coll1 << coll2, because a collection is more than just a set of its members. We should support coll1.members << coll2.

**Comment by jcoyne** [comment]
There's no reason we couldn't update the code to support coll1.objects << obj1

**Comment by elrayle** [comment]
See https://github.com/projecthydra-labs/hydra-pcdm/issues/45 for more information on a previous discussion.  This was addressing the fact that there was code for << in collection and file, but it wasn't tested.  Rewriting to support coll1.collections << coll2 style is preferable from my perspective.

**Comment by jcoyne** [comment]
It would be simpler to remove the code now than to write tests for it and then remove the code and the tests.

**Comment by elrayle** [comment]
What would be the process for appending vs. setting?

appending:
```
coll1.collections << coll2
```

setting:
```
coll1.collections = coll1.collections + coll2
```

I understood using the setting method was undesirable because it is inefficient and rewrites all proxies.

**Comment by elrayle** [comment]
The other option is to abstract this into a service object.
```
AddCollectionToCollection( parent_collection, child_collection )
  # validate
  parent_collection.members << child_collection
```

**Comment by elrayle** [comment]
Services have been added that provide the append functionality.  See https://github.com/projecthydra-labs/hydra-pcdm/pull/93
