### ISSUE TITLE
change type specific getters to return AssociationProxy

### ISSUE THREAD

**Issue by elrayle** [projecthydra-labs/hydra-pcdm#89]
Modify type specific setters to return AssociationProxy which reponds to #=, #==, #<<, etc

Example change for Collection...
```
AssociationProxy.new(self, :collections)
```

Also remove the companion setter methods.

**Comment by flyingzumwalt** [comment]
So, for example `collection.objects` and `collection.collections` will each return AssociationProxy objects that are configured to filter the members accordingly.

Related to #87, #84, #45

**Comment by terrellt** [comment]
It seems reasonably possible to make a FilteringAssociation that plays off the existing members association.

**Comment by flyingzumwalt** [comment]
terrellt I like that idea, so then you could have a class look like this

```ruby
aggregates :members, predicate: RDFVocabularies::PCDMTerms.hasMember,
        class_name: "ActiveFedora::Base"
aggregation_filter :collections, :members, type: "Collection"
```
(or something like that...)

**Comment by elrayle** [comment]
Several questions:
* Does AssociationProxy exist?  I couldn't find it in activefedora or activefedora-aggregation
* How would aggregation_filter know what a "Collection" is?  We don't validate off of class.  The validation check rdf_type.
* How would "Collection" type be validated when using the #= and #<< methods?

**Comment by jcoyne** [comment]
No, that code doesn't exist yet. It would be similar to how indirectly_contains/directly_contains works now. You could look there for inspiration. Since there is no code yet, the implementer can choose how to best do the validation.

**Comment by elrayle** [comment]
My concern is that even when the AssociationProxy exists, it will be for members as a whole and not allow for validation.

```
generic_works = _how_ever_we_get_and_filter_generic_works_   # returning an AssociationProxy

generic_works << a_generic_file   # would be allowed because there is no check beyond AF:Base class

**Comment by flyingzumwalt** [comment]
I didn't realize that AssociationProxy wasn't implemented yet.  For this
sprint, is it necessary to have these filtered getters and setters?  It
seems like something we should mark as out of scope so that we can focus on
things that are in the critical path of getting Sufia to work with
hydra-works.

Addressing @elrayle's specific comment about validation, I assumes that the
filtered association proxies would rely on the existing aggregation
(members) for the setter, which would apply all of the validation for that
aggregation.

**Comment by elrayle** [comment]
This is related to https://github.com/projecthydra-labs/hydra-pcdm/pull/93 which implements services for get/set operations.

**Comment by elrayle** [comment]
While implementing remove related objects services, errors occurred due to the fact that related_objects returns the AssociationProxy.  GetRelatedObjectsFromCollection/Object were updated to return an array to make their behavior consistent with that for collections and objects.  With services for basic CRUD, what unique benefits does passing the AssociationProxy to apps have that outways the separation of low level model implementation from higher level processing.  Passing AssociationProxy will make code maintenance more difficult when changes are made to the lowest persistence level.  One of the purposes of the PCDM and Hydra:Works gems should be to handle low level translations.  If next year, we use something other than AssociationProxies, the code that has to change are the services.  The apps that use the services should have no, or at least minimal, changes required.

**Comment by terrellt** [comment]
@elrayle Is this closed?

**Comment by elrayle** [comment]
Replaced by implementation of the filter associations.  This is no longer an issue.
